"""empty message

Revision ID: 357da406408e
Revises: 
Create Date: 2018-02-28 01:35:51.627364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357da406408e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('plain_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'plain_text')
    # ### end Alembic commands ###
